macro(mylib_enable_ipo)
    message(STATUS "Enabling interprocedural optimization (IPO)")
    include(CheckIPOSupported)
    check_ipo_supported(RESULT result OUTPUT output)
    if(result)
        message(STATUS "Enabling interprocedural optimization (IPO) - enabled")
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
    else()
        message(STATUS "Enabling interprocedural optimization (IPO) - failure: ${output}")
    endif()
endmacro()
